export const data = [
    {
        id: 1,
        titulo: "Problema de Conexão à Internet",
        descricao: "Usuário relata perda de conexão à internet após atualização do sistema.",
        conclusao: "Reconfiguração do roteador e atualização dos drivers de rede resolveu o problema.",
    },
    {
        id: 2,
        titulo: "Erro ao Acessar Sistema de Gestão",
        descricao: "Usuário não consegue acessar o sistema ERP. Erro de credenciais.",
        conclusao: "Redefinição da senha e verificação de políticas de segurança.",
    },
    {
        id: 3,
        titulo: "Impressora Não Responde",
        descricao: "Fila de impressão acumula e impressora não responde.",
        conclusao: "Reconexão da impressora à rede e reconfiguração.",
    },
    {
        id: 4,
        titulo: "Configuração de E-mail",
        descricao: "Ajuda necessária para configurar e-mail corporativo no Outlook.",
        conclusao: "E-mail configurado e integração com calendário concluída.",
    },
    {
        id: 5,
        titulo: "Falha no Backup Automático",
        descricao: "Sistema de backup não realizou execuções programadas.",
        conclusao: "Reparo na conexão com o servidor de backup.",
    },
    {
        id: 6,
        titulo: "Tela Azul no Windows",
        descricao: "Usuário relata tela azul frequente durante o uso do sistema.",
        conclusao: "Atualização dos drivers e verificação de integridade do sistema.",
    },
    {
        id: 7,
        titulo: "Erro na Instalação de Software",
        descricao: "Erro ao tentar instalar software de gestão de projetos.",
        conclusao: "Verificação de permissões e reinstalação corrigiram o problema.",
    },
    {
        id: 8,
        titulo: "Senha Expirada",
        descricao: "Usuário não consegue acessar o sistema devido à senha expirada.",
        conclusao: "Senha redefinida com sucesso.",
    },
    {
        id: 9,
        titulo: "Lentidão na Rede",
        descricao: "Rede está muito lenta, dificultando o acesso a sistemas online.",
        conclusao: "Verificação de pontos de acesso e otimização da rede resolveram o problema.",
    },
    {
        id: 10,
        titulo: "Problema com Antivírus",
        descricao: "Antivírus está bloqueando arquivos de trabalho importantes.",
        conclusao: "Ajustes nas políticas de segurança do antivírus.",
    },
    {
        id: 11,
        titulo: "Computador Não Liga",
        descricao: "Usuário relata que o computador não está ligando.",
        conclusao: "Substituição da fonte de alimentação e testes realizados.",
    },
    {
        id: 12,
        titulo: "Monitor Não Exibe Imagem",
        descricao: "Monitor do usuário não exibe imagem, mesmo com o computador ligado.",
        conclusao: "Cabo HDMI substituído e monitor funcionando normalmente.",
    },
    {
        id: 13,
        titulo: "Erro ao Sincronizar Arquivos",
        descricao: "Problema na sincronização de arquivos com o OneDrive.",
        conclusao: "Sincronização reconfigurada e ajustes de conexão aplicados.",
    },
    {
        id: 14,
        titulo: "Problema com Teclado",
        descricao: "Algumas teclas do teclado não estão funcionando corretamente.",
        conclusao: "Substituição do teclado por um novo.",
    },
    {
        id: 15,
        titulo: "Erro ao Acessar VPN",
        descricao: "Usuário não consegue acessar a rede VPN da empresa.",
        conclusao: "Atualização do cliente VPN e configuração do perfil.",
    },
    {
        id: 16,
        titulo: "Sistema Travando Frequentemente",
        descricao: "Sistema trava com frequência durante o uso de planilhas.",
        conclusao: "Aumento de memória RAM e limpeza de arquivos temporários.",
    },
    {
        id: 17,
        titulo: "Problema na Conexão Bluetooth",
        descricao: "Usuário não consegue conectar dispositivos Bluetooth ao computador.",
        conclusao: "Atualização dos drivers de Bluetooth resolveu o problema.",
    },
    {
        id: 18,
        titulo: "Erro na Impressão de PDF",
        descricao: "Erro ao tentar imprimir arquivos PDF em rede.",
        conclusao: "Reinstalação dos drivers de impressora corrigiu o problema.",
    },
    {
        id: 19,
        titulo: "Rede Wi-Fi Intermitente",
        descricao: "Conexão Wi-Fi cai intermitentemente, dificultando o trabalho.",
        conclusao: "Ajustes na configuração do roteador e troca de canal Wi-Fi.",
    },
    {
        id: 20,
        titulo: "Aplicativo Não Abre",
        descricao: "Usuário relata que o aplicativo de comunicação interna não abre.",
        conclusao: "Reinstalação do aplicativo e verificação de permissões.",
    },
    {
        id: 21,
        titulo: "Disco Cheio",
        descricao: "Usuário não consegue salvar arquivos, pois o disco está cheio.",
        conclusao: "Limpeza de arquivos temporários e migração para armazenamento na nuvem.",
    },
    {
        id: 22,
        titulo: "Erro ao Exportar Dados",
        descricao: "Erro ao tentar exportar relatórios do sistema de gestão.",
        conclusao: "Correção de bug no software e reconfiguração do formato de exportação.",
    },
    {
        id: 23,
        titulo: "Microfone Não Funciona",
        descricao: "Microfone do usuário não está funcionando durante videochamadas.",
        conclusao: "Reinstalação dos drivers de áudio e testes bem-sucedidos.",
    },
    {
        id: 24,
        titulo: "Erro de Autenticação",
        descricao: "Usuário não consegue autenticar no sistema de controle de horas.",
        conclusao: "Correção no banco de dados de autenticação e redefinição de senha.",
    },
    {
        id: 25,
        titulo: "Sistema de Backup Congelado",
        descricao: "Sistema de backup congela durante a execução das tarefas.",
        conclusao: "Reinicialização do sistema e verificação de integridade dos backups.",
    },
    {
        id: 26,
        titulo: "Erro de Certificado SSL",
        descricao: "Usuário não consegue acessar site interno devido a erro de certificado SSL.",
        conclusao: "Atualização do certificado SSL no servidor web.",
    },
    {
        id: 27,
        titulo: "Problema ao Conectar Projetor",
        descricao: "Usuário não consegue projetar a tela em uma reunião.",
        conclusao: "Atualização dos drivers de vídeo e ajuste nas configurações de projeção.",
    },
    {
        id: 28,
        titulo: "Relógio do Sistema Desconfigurado",
        descricao: "Relógio do sistema está desatualizado, afetando o login no sistema.",
        conclusao: "Sincronização com o servidor NTP corrigiu o problema.",
    },
    {
        id: 29,
        titulo: "Problema de Rede Local",
        descricao: "Usuário não consegue acessar pastas compartilhadas na rede local.",
        conclusao: "Verificação de permissões e reconfiguração do compartilhamento de rede.",
    },
    {
        id: 30,
        titulo: "Perda de Arquivos",
        descricao: "Usuário relata perda de arquivos após atualização do sistema.",
        conclusao: "Recuperação de arquivos através do backup e restauração do sistema.",
    },
    {
        id: 31,
        titulo: "Erro no Cliente de E-mail",
        descricao: "Usuário não consegue enviar e-mails através do cliente.",
        conclusao: "Verificação das configurações SMTP e correção de credenciais.",
    },
    {
        id: 32,
        titulo: "Dispositivo USB Não Reconhecido",
        descricao: "Usuário tenta conectar um dispositivo USB, mas o sistema não o reconhece.",
        conclusao: "Atualização dos drivers USB e testes bem-sucedidos.",
    },
    {
        id: 33,
        titulo: "Erro de Sincronização no Google Drive",
        descricao: "Arquivos não estão sincronizando corretamente com o Google Drive.",
        conclusao: "Reinstalação do cliente Google Drive e ajuste das configurações de sincronização.",
    },
    {
        id: 34,
        titulo: "Problema na Ligação de Videoconferência",
        descricao: "Usuário relata que não consegue ouvir os participantes da videoconferência.",
        conclusao: "Reconfiguração de áudio e testes realizados com sucesso.",
    },
    {
        id: 35,
        titulo: "Erro de Impressão em Rede",
        descricao: "Impressora de rede não está listada entre as opções de impressão.",
        conclusao: "Reconfiguração da impressora e ajustes nas permissões de rede.",
    },
    {
        id: 36,
        titulo: "Erro de Conexão no Banco de Dados",
        descricao: "Erro ao conectar ao banco de dados de produção.",
        conclusao: "Verificação das permissões de acesso e reinicialização do banco de dados.",
    },
];
